import = [
  "/home/sachin/.config/alacritty/themes/{{theme}}.toml",
  "/home/sachin/.config/alacritty/fonts.toml"
]

live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.98
startup_mode = "Windowed"

[window.dimensions]
columns = 111
lines = 23

[window.padding]
x = 18
y = 18
