[font]
size = 10

[font.bold]
family = "{{term_font}}"
style = "Bold"

[font.bold_italic]
family = "{{term_font}}"
style = "Bold Italic"

[font.italic]
family = "{{term_font}}"
style = "Italic"

[font.normal]
family = "{{term_font}}"
style = "Regular"
