[font]
size = 11

[font.bold]
family = "ShureTechMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "ShureTechMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "ShureTechMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "ShureTechMono Nerd Font"
style = "Regular"
