#!/bin/bash

help() {
	notify-send "sxiv keys :" " <ctrl-x> + key
	b - set wallpaper on primary monitor
	m - set wallpaper on external monitor
	d - delete file 
	c - copy to clipboard
	g - open in gimp
	v - play video
	h - help " -i "*"
}

while read file; do
	case "$1" in
		"b") cp -f "$file" ~/.config/bg.png                 ;; # set wallpaper ( primary monitor )
		"m") cp -f "$file" ~/.config/bg2.png                ;; # set wallpaper ( external monitor )
		"c") echo "$file" | wl-copy -p                      ;; # copy to clipboard
		"g") gimp "$file" & pkill sxiv                      ;; # open in image editor (gimp)
		"v") echo "$file" && pkill sxiv                     ;; # print file name to stdout
		"d") trash-cli "$file"                              ;; # delete file
		"h") help                                           ;; # help 
	esac
done

