#!/bin/sh

xrdb merge ~/.Xresources 
# xbacklight -set 30 &
feh --bg-fill ~/.config/bg.png &
xset r rate 250 70 &
picom &
# nm-applet &
xrandr --output eDP-1-0 --primary --mode 1920x1080 --pos 0x1080 --output HDMI-0 --mode 1920x1080 --pos 0x0 --above eDP-1-0

# dash ~/.config/chadwm/scripts/bar.sh &
while type chadwm >/dev/null; do chadwm && continue || break; done
