#!/usr/bin/env bash

# autostart = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
pgrep -x sxhkd >/dev/null || sxhkd -c "$HOME"/.config/bspwm/keymaps "$HOME"/.config/sxhkd/sxhkdrc &
pgrep -x polybar >/dev/null || polybar -r &

# monitor & workspace configuration = = = = = = = = = = = = = = = = = = = = = = = = =

MONITOR01="eDP-1-0"
MONITOR02="HDMI-0"

if xrandr | grep -q "^$MONITOR02 connected"; then
	bspc monitor $MONITOR01 -d 1 2
	bspc monitor $MONITOR02 -d 3 4 5
	feh --no-fehbg --bg-scale "${HOME}"/.config/bg.png "${HOME}"/.config/bg2.png
else 
	bspc monitor $MONITOR01 -d 1 2 3 4 5
	feh --no-fehbg --bg-scale ${HOME}/.config/bg.png
fi


# bspwm configuration = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
bspc config border_width 5
bspc config window_gap 0
bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# bspwm colors = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
bspc config focused_border_color   "#816ab7" #"#806D60"  #"$YELLOW" 
bspc config normal_border_color    "#424450" #$BACKGROUND"
bspc config active_border_color     "$MAGENTA"
bspc config presel_feedback_color   "$GREEN"

# window rules = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
# bspc rule -a zen-beta desktop='^2' follow=on focus=on
# bspc rule -a alacritty desktop='^1' follow=on focus=on
bspc rule -a Portmaster state=floating manage=on focus=on
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Conky state=floating manage=off
bspc rule -a Indicator-stickynotes state=floating manage=off
bspc rule -a zoom state=floating manage=on
bspc rule -a sonata state=floating manage=on
bspc rule -a Sxiv state=floating manage=on
bspc rule -a floatAlacritty state=floating rectangle=600x300+1300+760
bspc rule -a scpad sticky=on state=floating rectangle=1916x400+0+0
bspc rule -a Gcolor3 state=floating sticky=on  manage=on
bspc rule -a scrcpy state=floating sticky=on  manage=on
bspc rule -a Yad state=floating sticky=on  manage=on border=off 
bspc rule -a Ulauncher state=floating border=off

# end configuration = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
