#!usr/bin/env bash 
#
#

# global key bindings  = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  

# Terminal tmux (kitty)
super + Return
  pgrep kitty && bspc desktop -f "1" || kitty #-e tmux -u attach -t "arch" >/dev/null || tmux -u new -s "arch" 

# Terminal (Alacritty)
super + shift + Return
  alacritty

# rofi launcher & menus  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

# Rofi App Launcher
super + d
  ~/.config/rofi/launchers/type-7/launcher.sh

super + {r,c,e,n,w,s} 
	rofi -show {run,calc,emoji,wifimenu,window,search}  

alt + c
	rofi-menu clip

# power menu 
super + x
   $HOME/.local/scripts/powermenu 

# display 
super + m 
  $HOME/.local/scripts/exmon

# wifimenu
super + alt + i
   $HOME/.local/scripts/conwifi 

# bluetooth menu
super + alt + b
   $HOME/.local/scripts/bluemenu

# media control 
super + alt + m
   $HOME/.config/rofi/music/music

# tool launcher 
super + l 
   $HOME/.local/tools/launcher

# applications - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

# Launch Apps
super + shift + {f,e,b}
	{pcmanfm,code,foliate}

# zen-browser
super + shift + w
  pgrep zen && bspc desktop -f "2" || zen-browser
super + w
  pgrep zen && bspc desktop -f "2" || zen-browser

# scratch pad 
alt + Return
   ~/.local/scripts/scpad &

# Terminal Apps
ctrl + alt + {v,n,r,h,g,f}
	alacritty -e {nvim,newsboat,ranger,htop,glances,lfub}

# terminal apps in floating window 
ctrl + alt + {p,c}
   alacritty --class floatAlacritty -e {pulsemixer,ncmpcpp}

# Color Picker
super + p
	yad --color | xclip -sel c

# image viewvier (sxiv)
super + i
	sxiv -btrg 1047x570 $HOME/pix/walls

# screenkey toggle
super + shift + K
    {screenkey --opacity 0.2 --font-color yellow -s small, killall screenkey}

# web applications - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

super + alt + a
   xclip -o | grep "^http" && google-chrome-stable --app="$(xclip -o)" || notify-send "sxhkd" "no url found!"

super + alt + y 
   google-chrome-stable --app="https://youtube.com"

super + alt + l 
   google-chrome-stable --app="https://www.linkedin.com"

super + alt + p
   google-chrome-stable --app="https://pastebin.com"

super + alt + d
   google-chrome-stable --app="https://discord.com/channels/@me"

super + alt + n 
   google-chrome-stable --app="https://www.notion.so/sachinhole"

super + alt + r
   google-chrome-stable --app="https://youtube.com/playlist?list=PLu71SKxNbfoDqgPchmvIsL4hTnJIrtige&si=UaMKTcKiZfkFEZ4J"

super + alt + w   
   google-chrome-stable --app="https://web.whatsapp.com"

super + alt + s
   google-chrome-stable --app="https://scrimba.com/dashboard"

super + alt + t
  google-chrome-stable --app="https://youtube.com/playlist?list=PL8p2I9GklV44sj_Ikp8jQSvwD-m9htnHT&si=FqUBYGgwNc2I9kb8"

super + alt + e
  google-chrome-stable --app="https://excalidraw.com"

super + alt + o 
  barve-browser --app="https://exercism.org"

# system keys - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

# make sxhkd reload its configuration files:
super + shift + r
	pkill -USR1 -x sxhkd

# Take a screenshot
Print
  flameshot full -p $HOME/pix/shots/shot:$(date +%s).png

# Take screenshot of area
super + Print
	flameshot gui #-p $HOME/pix/shots/shot:$(date +%s).png

# Take screenshot in 5 second
alt + Print
  flameshot full -d 5000 -p $HOME/pix/shots/shot:$(date +%s).png

# Take screenshot in 10 second
ctrl + shift + Print	
	flameshot full -d 10000 -p $HOME/pix/shots/shot:$(date +%s).png

# Brighness control
XF86MonBrightness{Up,Down}
	brightnessctl{ set +5%, set 5%-}
	# xbacklight{ --inc 5, --dec 5}

# Volume control
XF86Audio{RaiseVolume,LowerVolume}
	pulsemixer{ --change-volume +5, --change-volume -5 }

XF86AudioMute
	pulsemixer --toggle-mute

# Music control
XF86Audio{Next,Prev,Play,Stop}
	mpc {next,prev,toggle,stop}

# Toggle polybar
super + b
    {polybar-msg cmd hide && bspc config -m eDP1 top_padding +0 ,\
    polybar-msg cmd show && bspc config -m eDP1 top_padding 36}

super + shift + m
  {brightnessctl set 0% ,brightnessctl set 30%, brightnessctl set 60%}

super + z
  {bspc config window_gap 100, bspc config window_gap 7, bspc config window_gap 0}

# global key bindings  = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  

