#!/bin/bash
#

xrdb merge ~/.Xresources 
# xset r rate 230 50 &

# bash ~/dotfiles/dwm/scripts/bar &

# set display
xrandr --output eDP-1-0 --primary --mode 1920x1080
xrandr --output HDMI-0 --rotate left --mode 1920x1080 --right-of eDP-1-0

picom &
nm-applet &

exec awesome # start bspwm

# start, restart on crash, logout when exit cleanly
# while type dwm >/dev/null; do 
# 	exec dwm && continue || break;
# done

