#!/usr/bin/env bash

[[ -z ${DOTFILES} ]] && DOTFILES=${HOME}/.local/dotter

function _dotter {
	if cd ${DOTFILES}; then
		./dotter ${@}
		exit
	fi
}

function _edit {
	find ${DOTFILES} -type f | fzf | xargs -I '{}' nvim {}
}

while [[ ${#} > 0 ]]; do
	case ${1} in
	'edit')
		_edit
		shift
		;;
	'lf')
		lf ${DOTFILES}
		shift
		;;
	*)
		_dotter ${*}
		shift
		;;
	esac
done
