#!/bin/sh

# choose and set alacritty theme
function atheme {
    /bin/cat ${HOME}/.config/alacritty/colorschemes/$(/bin/ls ${HOME}/.config/alacritty/colorschemes | /bin/fzf ) > ${HOME}/.config/alacritty/colors.yml
}

# scan wifi
function swifi {
    nmcli device wifi rescan && nmcli device wifi list
}

# connect to wifi
function cwifi {
    if [ ${*} ] ; then
        nmcli device wifi connect "${*}"
    else 
        nmcli device wifi connect $(swifi | tail -n +2 | fzf | tr '*' ' ' | awk '{print $2}')
    fi
}

# web serach
function gg {
   ( brave --app="https://www.google.com/search?q=${*}" & )
}

# :help
_help() {
    echo help!
}

# main
${@} ; exit
