#!/bin/bash

# Define the directory to monitor
DIRECTORY="${HOME}/sync/notes"

# Define your git repository URL
REPO_URL="git@github.com:holesachin/notes.git"

# Define the commit message
COMMIT_MESSAGE="$(date)"

# shh private key path 
SSH_PRIVATE_KEY="${HOME}/.ssh/lnx_id_rsa"

# wait after file changes
WAIT=7

# Function to perform git add, commit, and push
function git_auto_commit() {
    local directory=$1
    local event=$2
    local file=$3

    cd "$directory" || exit 1  # Change to the directory

    # Check if there are any changes to commit
    if [[ -n "$(git status --porcelain)" ]]; then
        git add --all .

        # Determine the type of change
        if [[ $event == "CREATE" ]]; then
            commit_message="CREATED $file"
        elif [[ $event == "MODIFY" ]]; then
            commit_message="MODIFYED $file"
        else
            commit_message="CHANGED $file"
        fi

        git commit -m "$commit_message"
        GIT_SSH_COMMAND="ssh -i ${SSH_PRIVATE_KEY}" git push origin HEAD
    fi
}


# Monitor directory changes
inotifywait -m -r -e modify,create,delete --format '%w %e %f' "$DIRECTORY" |
while read -r directory event file; do
   sleep ${WAIT}m
   echo "Change detected in $directory$file, committing changes..."
   git_auto_commit "$directory" "$event" "$file"
done

