#!/usr/bin/env bash
#
# monx - monitors control scripts

MONITOR_CONF=${MONITOR_CONF:="${HOME}/.config/hypr/monitors.conf"}

# Enable all Monitors
function monx_enable_all {
   sed -i '/monitor=.*,disable/d' "${MONITOR_CONF}"
}

# Enable Specific Monitor
function monx_enable {
   sed -i "/monitor=${1},disable/d" "${MONITOR_CONF}"
}

# Disable Monitor
function monx_disable {
	echo "monitor=${1},disable" >> "${MONITOR_CONF}"
}

# Toggle Monitor
function monx_toggle {
	if grep -q "monitor=${1},disable" "${MONITOR_CONF}"; then
		monx_enable "${1}"
	else
		monx_disable "${1}"
	fi
}


# Options

case $1 in
	enable) monx_enable $2 ;;
	disable) monx_disable $2 ;;
	enable_all) monx_enable_all ;;
	toggle) monx_toggle $2 ;;
	*) echo "monx - monitors control scripts"
		echo "Usage: monx [enable|disable|enable_all]"
		exit 1 ;;
esac
