#!/bin/sh

export XAUTHORITY=/home/sachin/.Xauthority
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

# Check if the computer is running on AC power or on battery
if [ $(cat /sys/class/power_supply/ACAD/online) -eq 1 ]; then
	# If AC power is detected, increase the screen brightness
	brightnessctl -q s 70%
else
	# If running on battery, decrease the screen brightness
	brightnessctl -q s 21%
fi
