

music_directory "~/music"
playlist_directory "~/.config/mpd/playlists"
db_file "~/.config/mpd/mpd.db"
log_file "~/.config/mpd/mpd.log"
pid_file "~/.config/mpd/mpd.pid"
state_file "~/.config/mpd/mpdstate"

auto_update "yes"
restore_paused "yes"

# pulse audio 
#audio_output {
#        type "pulse"
#        name "pulse audio"
#}

# pipewire audio  
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}

# audio output for equlizer
audio_output {
	type                    "fifo"
	name                    "my_fifo"
	path                    "/tmp/mpd.fifo"
	format                  "44100:16:2"
}

# bind_to_address     "/run/mpd/socket"
bind_to_address "0.0.0.0"
port "6600"
