[helpers]

[default]
depends = []

[default.files]
background = { target = "~/.config/", type = "symbolic" }
bspwm = "~/.config/bspwm"
espanso = ""
flameshot = "~/.config/flameshot"
foot = "~/.config/foot"
geany = "~/.config/geany"
greetd = "~/.config/regreet"
lite-xl = ""
mako = "~/.config/mako"
mpd = ""
mpv = ""
ncmpcpp = ""
neofetch = "~/.config/neofetch"
nvim = "~/.config/nvim"
nwg-displays = "~/.config/nwg-displays"
nwg-drawer = "~/.config/nwg-drawer"
nwg-panel = "~/.config/nwg-panel"
pcmanfm = ""
rofi = ""
scripts = "~/.local/scripts"
shell = "~/.config/shell"
swaylock = "~/.config/swaylock"
sxhkd = "~/.config/sxhkd"
sxiv = "~/.config/sxiv"
tmux = "~/.config/tmux"
tofi = "~/.config/tofi"
udev = ""
ulauncher = ""
wayfire = ""
wf = ""
xdg = "~/.config/"

[default.variables]


[hypr]
depends = [ "alacritty", "kitty", "bash", "zsh", "wofi", "lf", "waybar" ]

[hypr.files]
hypr = "~/.config/hypr"

[hypr.variables]
background = ""

[bash.files]
"bash/bashrc" = "~/.bashrc"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[alacritty.files]
alacritty = "~/.config/alacritty"

[alacritty.variables]
theme = "one_dark"
term_font = "JetBrainsMono Nerd Font"

[kitty.files]
kitty = "~/.config/kitty"

[kitty.variables]
kitty_theme = "OneDark"

[wofi.files]
wofi = "~/.config/wofi"

[lf.files]
lf = { target = "~/.config/lf", type = "symbolic" }

[waybar.files]
waybar = "~/.config/waybar"



