[helpers]

[default]
depends = []

[default.files]
background = { target = "~/.config/", type = "symbolic" }
bspwm = "~/.config/bspwm"
espanso = ""
flameshot = "~/.config/flameshot"
foot = "~/.config/foot"
geany = "~/.config/geany"
greetd = "~/.config/regreet"
lite-xl = ""
mako = "~/.config/mako"
mpd = ""
mpv = ""
ncmpcpp = ""
neofetch = "~/.config/neofetch"
nvim = "~/.config/nvim"
nwg-displays = "~/.config/nwg-displays"
nwg-drawer = "~/.config/nwg-drawer"
nwg-panel = "~/.config/nwg-panel"
pcmanfm = ""
rofi = ""
scripts = "~/.local/scripts"
shell = "~/.config/shell"
swaylock = "~/.config/swaylock"
sxhkd = "~/.config/sxhkd"
sxiv = "~/.config/sxiv"
tmux = "~/.config/tmux"
tofi = "~/.config/tofi"
udev = ""
ulauncher = ""
wayfire = ""
wf = ""
xdg = "~/.config/"

[default.variables]


[hypr]
depends = [ "alacritty", "kitty", "bash", "zsh", "wofi", "lf", "waybar" ]

[hypr.files]
hypr = "~/.config/hypr"

[hypr.variables]
background = ""

[bash.files]
"bash/bashrc" = "~/.bashrc"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[alacritty.files]
alacritty = "~/.config/alacritty"

[alacritty.variables]
theme = "one_dark"
term_font = "JetBrainsMono Nerd Font"

[kitty.files]
kitty = "~/.config/kitty"

[kitty.variables]
# themes: 3024_Day 3024_Night AdventureTime Afterglow AlienBlood Alucard Apprentice Argonaut Arthur AtelierSulphurpool Atom AtomOneLight ayu ayu_light ayu_mirage Batman Belafonte_Day Belafonte_Night BirdsOfParadise Blazer 
# Borland Bright_Lights Broadcast Brogrammer C64 Chalkboard Chalk Ciapre CLRS Cobalt2 Cobalt_Neon CrayonPonyFish Dark_Pastel Darkside Desert DimmedMonokai DotGov Dracula Dumbledore Duotone_Dark Earthsong Elemental ENCOM 
# Espresso Espresso_Libre Fideloper FishTank Flat Flatland Floraverse FrontEndDelight FunForrest Galaxy Github Glacier GoaBase Grape Grass gruvbox_dark gruvbox_light Hardcore Harper Highway Hipster_Green Homebrew Hurtado 
# Hybrid IC_Green_PPL IC_Orange_PPL idleToes IR_Black Jackie_Brown Japanesque Jellybeans JetBrains_Darcula Kibble Later_This_Evening Lavandula LiquidCarbon LiquidCarbonTransparent LiquidCarbonTransparentInverse Man_Page 
# Material MaterialDark Mathias Medallion Misterioso Molokai MonaLisa Monokai_Classic Monokai Monokai_Pro Monokai_Pro_(Filter_Machine) Monokai_Pro_(Filter_Octagon) Monokai_Pro_(Filter_Ristretto) Monokai_Pro_(Filter_Spectrum) 
# Monokai_Soda N0tch2k Neopolitan Neutron NightLion_v1 NightLion_v2 Nova Novel Obsidian Ocean OceanicMaterial Ollie OneDark Parasio_Dark PaulMillr PencilDark PencilLight Piatto_Light Pnevma Pro Red_Alert Red_Sands 
# Relaxed_Afterglow Renault_Style Renault_Style_Light Rippedcasts Royal Seafoam_Pastel SeaShells Seti Shaman Slate Smyck snazzy SoftServer Solarized_Darcula Solarized_Dark Solarized_Dark_Higher_Contrast Solarized_Dark_-_Patched 
# Solarized_Light Source_Code_X Spacedust SpaceGray SpaceGray_Eighties SpaceGray_Eighties_Dull Spiderman Spring Square Sundried Symfonic Tango_Dark Tango_Light Teerb Thayer_Bright The_Hulk Tomorrow Tomorrow_Night_Blue 
# Tomorrow_Night_Bright Tomorrow_Night Tomorrow_Night_Eighties ToyChest Treehouse Twilight Ubuntu Urple Vaughn VibrantInk WarmNeon Wez WildCherry Wombat Wryan Zenburn
kitty_theme = "Batman"

[wofi.files]
wofi = "~/.config/wofi"

[lf.files]
lf = { target = "~/.config/lf", type = "symbolic" }

[waybar.files]
waybar = "~/.config/waybar"



